# Keybindings -----------------------------------------------------------------
$mod = SUPER

bind = $mod, BACKSPACE, exec, swaybg -i ~/Pictures/wallpapers/wallpapers/DARKS/shelter-from-the-rain-by-ayuli2424-1920×1080.jpg
bind = $mod SHIFT, BACKSPACE, exec, swaybg -i ~/Pictures/wallpapers/wallpapers/DARKS/moodyforest.png

bind = $mod, Return, exec, kitty
bind = $mod, B, exec, firefox
bind = $mod, D, exec, rofi -show drun
bind = $mod, C, killactive,
bind = $mod, Q, exit,
bind = $mod, M, exec, spotify
bind = $mod SHIFT, F, togglefloating,
bind = $mod, F, fullscreen
# bind = $mod, E, exec, nautilus
bind = $mod, P, pseudo, # split mode
bind = $mod, S, togglesplit, # vertical/horizontal
bind = $mod, R, exec, sh -c "hyprctl reload && notify-send 'Hyprland' 'Config reloaded'"
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Workspace navigation --------------------------------------------------------
bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, j, movefocus, d
bind = $mod, k, movefocus, u

# Workspaces ------------------------------------------------------------------
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Misc ------------------------------------------------------------------------
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
