source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/exec-once.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/animations.conf

# Environment -----------------------------------------------------------------
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,capitaine-cursors
# env = GTK_THEME,Adwaita:dark
env = GTK_THEME,Gruvbox-Dark
env = QT_QPA_PLATFORMTHEME,qt5ct

# Input -----------------------------------------------------------------------
input {
    kb_layout = es
    kb_variant =
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
        tap-to-click = true
    }
}

# General look ----------------------------------------------------------------
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = rgb(98971a)
    col.inactive_border = rgba(313244aa)
    layout = dwindle
}

decoration {
    rounding = 6
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.92

    dim_inactive = true
    dim_strength = 0.08

    shadow {
        enabled = true
        range = 10
        render_power = 2
        color = rgba(00000066)
    }

    blur {
        enabled = true
        size = 3
        passes = 1
        noise = 0.01
        contrast = 1.0
        brightness = 1.0

        vibrancy = 0.1696
    }
}
