general {
    ignore_dbus_inhibit = false
  }

listener {
    timeout = 300
    on-timeout = bash -c '[ "$(playerctl status 2>/dev/null)" != "Playing" ] && hyprctl dispatch dpms off eDP-1'
    on-resume = hyprctl dispatch dpms on eDP-1
}
