font_family Hack Nerd Font
font_size 14.0
include themes/
include ~/.config/kitty/themes/current-theme.conf
enable_audio_bell no
background_opacity 0.80
cursor_trail 3
confirm_os_window_close 0
background_blur 1
url_style curly
remember_window_size no
initial_window_width 78c
initial_window_height 23c
window_padding_width 3
cursor_blink_interval 0
scrollbar_handle_opacity 0
scrollbar_track_opactiy 0
scrollbar_track_hover_opactiy 0
sync_to_monitor no
