font_family Hack Nerd Font
font_size 14.0
include themes/
include ~/.config/kitty/themes/current-theme.conf
enable_audio_bell no
background_opacity 0.85
cursor_trail 1
confirm_os_window_close 0
background_blur 1
