# Autostart -------------------------------------------------------------------
exec-once = waybar &
exec-once = copyq
exec-once = flameshot
# exec-once = picom &
# exec-once = swaybg -i ~/Pictures/wallpapers/wallpapers/DARKS/shelter-from-the-rain-by-ayuli2424-1920×1080.jpg 
exec-once = swaybg -i ~/Pictures/wallpapers/wallpapers/DARKS/moodyforest.png
exec-once = mako &
exec-once = hyprpaper &
# exec-once = nm-applet &
exec-once = blueman-applet --no-tray &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# exec-once = swayidle -w timeout 150 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' &
