# Monitor setup ---------------------------------------------------------------
# monitor=,preferred,auto,1

### BUILT-IN SCREEN
monitor = eDP-1, 1920x1080@60, 0x0, 1

### TV IN MY ROOM
monitor = HDMI-A-1, 1360x768@60, auto-left, 1

### TV IN LIVINGROOM
# monitor = X, X@X, auto-right, 1.6
